apiVersion: v1
kind: Service
metadata:
  name: microservice-result-service
spec:
  selector:
    app: microservice-result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: NodePort
